const DATABASE_NAME = '@carwash'

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_SCHEDULES= `${DATABASE_NAME}:schedules`;
// const COLLECTION_APPOINTMENT_SELECTED = `${DATABASE_NAME}:appointment_selected`;

export {
    COLLECTION_USERS,
    COLLECTION_SCHEDULES,
    // COLLECTION_APPOINTMENT_SELECTED
}